### ISSUE TITLE
min cpu freq

### ISSUE THREAD

**Issue by maej72** [LukasAddon/SpaceLemon-N910H-Kernel#1]
hello dev,
big fan of your work :D 

can you please make the minimum cpu frequency for little and big 200mhz?

**Comment by LukasAddon** [comment]
Hi !
why you need this feature ? it is no save more battery with 200mhz.
I can do, but why ?

**Comment by maej72** [comment]
really?
i thought it would save battery life ):
but if you can add it please

**Comment by LukasAddon** [comment]
when cores idle - they disconect from power. but you see in synapse minimum frequency  on cores. 
now processor woks fine, not need to make more min frequency.
When screen on processor not down to minimum frequency. 

But you can save energy, set in tab "CPU VOLT" voltage to lower in 2-3 step. And if your procssor can work  with low voltage it save battery.
