### ISSUE TITLE
Cpu wont go 2100mhz spontaneously

### ISSUE THREAD

**Issue by Moderndaycowboy** [LukasAddon/SpaceLemon-N910H-Kernel#10]
Not a big issue, Last kernel is rock stable.

The cpu wont go to 2100, even I make overclock.  ![screenshot_2017-08-31-10-45-48](https://user-images.githubusercontent.com/23087440/29912244-b01c9394-8e39-11e7-9dc3-da44923f6f03.png)

When I do this 
![screenshot_2017-08-31-10-47-22](https://user-images.githubusercontent.com/23087440/29912301-e4c20b06-8e39-11e7-9cf9-db806f3be0f0.png)

It works.

why does it happen?

**Comment by LukasAddon** [comment]
i see 2100 works, but problem to show it in stats )))
i will try to fix it in next release

**Comment by Moderndaycowboy** [comment]
:) you work a lot, thanks I appreciate.
