### ISSUE TITLE
Synapse

### ISSUE THREAD

**Issue by Moderndaycowboy** [LukasAddon/SpaceLemon-N910H-Kernel#2]
I am a big fan of your kernel too, it is the best kernel for note 4

1- UMS doesnt work properly, it is slower than MTP (on 2.3.2)
2- everytime Synapse try to revert back memory laptop mode idk why.
3- Also I cannot use Clear DVF cache button, synapse says it is RO (I use many programs to change RO to RW in system, nothing works. I use stock rom
4- When I change GPU to default to interactive or booster, sometimes games shut down for no reason.
5- I dont know it is a kernel problem but, I opened synapse and then I open something else, I f I open synapse again with its own icon synapse FC, If I open that with active applications no problem.

Also with antutu I got 70466 points thats just amazing. Thanks for your kernel.

Also, When will you release new version of your kernel?

**Comment by LukasAddon** [comment]
Thanks for issue ! 
1) UMS work with standart driver in kernel, i only enable this function. in old OS (win XP)  i can connect my phone and copy data.  maybe speed is slower. 

others errors i check and try to fix.

**Comment by Moderndaycowboy** [comment]
I can connect with UMS too, but the speed is very slow like 2.5 mb/s in my note 4.

My sd card is type 10, so it should be near 10mb/s I guess. I rather use MTP now.

May you think to make OC for CPU?

**Comment by LukasAddon** [comment]
my card have 5.2-7.5 mb/s on write.  only if i write one big file.
And 2.5-3.5 if i write many little files.
class 10  not always give us 10mb/s on write.

**Comment by LukasAddon** [comment]
> May you think to make OC for CPU?

in next version - no. maybe in future.

**Comment by Moderndaycowboy** [comment]
I see, thanks for of all those information

I found another bug, when I click synapse icon, I got a soft reboot today on my note 4

thats weird because it never happened until this time.

**Comment by LukasAddon** [comment]
My kernel have some function porting from  UK kernel (Android 5) and maybe parts of options in synapse not work. i fix or remove not working options in synapse

**Comment by Moderndaycowboy** [comment]
Hmm that is a big deal, I am using MM 
Everything works with synapse some of them are buggy. 

New issues
1. GPU underclock is not working properly, phone goes reboot instantly after a while. 
2. Zerolemon battery extended kernel shows a little incorrect values in some percentage. 

I have bought recently and you said that there is no calibration needed. When I try to charge battery holds on %100 a long time like 20min. Is there anything I can deal with that?

**Comment by Moderndaycowboy** [comment]
I will try to reset fuel gauge soon to fix that.

**Comment by LukasAddon** [comment]
> battery holds on %100 a long timу

Yes before battery show full charge , it show 100% long time. it is normal for Zerolemon battery

**Comment by Moderndaycowboy** [comment]
oh really okay then. 

Thanks for all help 

when will the new version come?

**Comment by LukasAddon** [comment]
i add root installer to kernel, suoersu apk and some fixes.
other fixes i will do later in 1-2 week
