### ISSUE TITLE
Fast Charge or not

### ISSUE THREAD

**Issue by Moderndaycowboy** [LukasAddon/SpaceLemon-N910H-Kernel#4]
Thanks for your amazing kernel, Should I use fast charge with your 2.4.18 spacelemon kernel?
is it harmful for that batttery?

**Comment by LukasAddon** [comment]
I didnt change charge driver. use fast charge only for standart battery. 
it is not only for my kernel. you should disable fast charge for extended battery.

**Comment by Moderndaycowboy** [comment]
Thanks for the information
