### ISSUE TITLE
DT2W issue

### ISSUE THREAD

**Issue by Moderndaycowboy** [LukasAddon/SpaceLemon-N910H-Kernel#5]
Swipe to sleep is always working, double tap to wake is not working sometimes. Why does it happen?

**Comment by LukasAddon** [comment]
because when phone deep sleep, you need first double tap to wake up processor and then double tap to  wake up screen  )))

**Comment by LukasAddon** [comment]
little bug. but  not battery drain

**Comment by Moderndaycowboy** [comment]
Oh God. Thanks for the information.
