### ISSUE TITLE
Delayed screen and touch issues

### ISSUE THREAD

**Issue by Moderndaycowboy** [LukasAddon/SpaceLemon-N910H-Kernel#6]
When I try to wake phone, sometimes I cannot make it woke. It is delayed like 10 seconds, not always!

Rarely, phones touch system is not working after I made woke the screen . To fix that issue I have to remove the battery. 
It annoys me, I didn't figure it out. 

For both issues I try to close swipe2sleep and DT2W. Also I closed Lcd power reduce. It didn't work.
Please help.

**Comment by Moderndaycowboy** [comment]
Those issues are valid for last update named 2.5.5 extended version.

**Comment by LukasAddon** [comment]
What firmware ?
try disable edge panels if you use note 7 port!!!

**Comment by Moderndaycowboy** [comment]
I use stock note 4 dpk1 Poland Rom, I don't have edge features

**Comment by Moderndaycowboy** [comment]
I mean N910CXXS2DPK1 this is the build number.

**Comment by LukasAddon** [comment]
minority people get this bug. i don't know yet, where is the problem in kernel

**Comment by Moderndaycowboy** [comment]
It causes during the call and it causes when I try to wake the phone from deep sleep , I think it is related with proximity sensor and something else I am not sure.

**Comment by Moderndaycowboy** [comment]
I have passed to Slovenia stock rom, the problem seemed to be faded.
