### ISSUE TITLE
DT2W issues..

### ISSUE THREAD

**Issue by talexop** [LukasAddon/SpaceLemon-N910H-Kernel#7]
Hello,
Thanks for this GREAT addon!!
I have noticed some issues.
-Proximity sensor does not disable dt2w.. Even If I block proximity with my finger d2tw still works.
-Double clicking to different screen areas can enable screen. It seems like the FEATHER pixels do not work as expected. I do a click on top left of the screen and one on bottom right and screen is on!

**Comment by LukasAddon** [comment]
Hi ! 
1) yes, maybe Proximity sensor does not disable dt2w. i check this.
2) yes, i fix it in next version.

thx for report!

**Comment by talexop** [comment]
Thanks! for you effort! Waiting for your new release!
