### ISSUE TITLE
rarely have soft reboot When enabled aggresive doze on v 2.12.0

### ISSUE THREAD

**Issue by Moderndaycowboy** [LukasAddon/SpaceLemon-N910H-Kernel#8]
the issue comes when I try to wake the phone from deep sleep, on 2.12.0 rarely phone stuck and goes to soft reboot. I use N910C

I have tested,

v 2.4.18 has no soft reboot issues. not at all.
v.2.5.5  has frequent soft reboot issues, when I try to wake the phone from deep sleep. Also that kernel have another problem with aggresive doze mode.
v2.12.0 has rare soft reboot issues, when I try to wake the phone from deep sleep.

**Comment by LukasAddon** [comment]
Hi, what firmware you use ? did you use another modules to tweak android ?

**Comment by Moderndaycowboy** [comment]
I use N910CXXU2S2DQC1 Poland firmware

I use L speed and greenify.

**Comment by LukasAddon** [comment]
i try to fix this issue. i will remove all old dt2w modules and rewrite code.
you can test in next version.

**Comment by Moderndaycowboy** [comment]
Thanks to you, I appreciated.

**Comment by LukasAddon** [comment]
Can you test new version ? i think bug fixed.

**Comment by Moderndaycowboy** [comment]
I downloaded the new version yesterday.

it is fixed, thanks :)

by the way one new issue, it is not important so much,

some games have little microstuttering issues in piano tiles 2, and skillful finger. ( I have ever observed)

I am on interactive governor which has little microstuttering, (which bioshock governor had more problem with microstuttering)

I can advise that change the default governor of kernel to interactive, it is more stable than bioshock.

in stock kernel no issues with it.

I suspect with arch power saving right now, or randomization. I am not sure which is the problem.

**Comment by LukasAddon** [comment]
randomization ? 
I can do randomization faster but less sequrity. i think i can make option in synapse

**Comment by LukasAddon** [comment]
now you can edit entropy levels in synapse. maybe it help

**Comment by Moderndaycowboy** [comment]
I will try those, thanks for your amazing kernel.

**Comment by LukasAddon** [comment]
in synapse (tab advanced)  set kernel entropy to 2048 / 2048
next (tab IO)  check enabled "Add Random"

check this settings and test some configurations

**Comment by Moderndaycowboy** [comment]
I did it, testing right now.

**Comment by Moderndaycowboy** [comment]
no luck, still have microstutterings.

**Comment by LukasAddon** [comment]
Try "perfomanse" governor .

**Comment by Moderndaycowboy** [comment]
I tried it works flawlessly.

**Comment by LukasAddon** [comment]
then i close issue.  try ask about governor settings on forum xda. you can edit settings in synapse after choice governor.
